name: Create Release
on:
  push:
    branches:
      - master

jobs:
  tagged-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          REPO_OWNER: Jakobis
